version: 0.2

phases:
  install:
    commands:
      - pip install bandit
      - yum install -y zip

  pre_build:
    commands:
      - echo "Running Security Scan..."
      - bandit -r . -f txt || true

  build:
    commands:
      - echo "Packaging application..."
      - zip function.zip lambda_function.py

artifacts:
  files:
    - function.zip
